SELECT
    BOOK.CATEGORY,
    sum(BOOK_SALES.SALES) as TOTAL_SALES
FROM
    BOOK
JOIN
    BOOK_SALES
WHERE
    BOOK.BOOK_ID = BOOK_SALES.BOOK_ID AND
    BOOK_SALES.SALES_DATE like "2022-01-%"
GROUP BY
    BOOK.CATEGORY
ORDER BY
    BOOK.CATEGORY;