SELECT
    info.INGREDIENT_TYPE,
    sum(TOTAL_ORDER) as TOTAL_ORDER
FROM
    FIRST_HALF as half
JOIN
    ICECREAM_INFO as info
WHERE
    half.FLAVOR = info.FLAVOR
GROUP BY
    info.INGREDIENT_TYPE
ORDER BY
    TOTAL_ORDER ASC;